services:
  - type: web
    name: infyra
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: infyra-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_PROVIDER
        value: filesystem
      - key: UPLOAD_FOLDER
        value: /var/lib/CTFd/uploads
      - key: LOG_FOLDER
        value: /var/log/CTFd
      - key: WORKERS
        value: "4"

databases:
  - name: infyra-db
    plan: free
    databaseName: infyra
    user: infyra_user
